# https://supabase.com/docs/guides/cli/config

[api]
enabled = true

[functions.add_sentence]
verify_jwt = false

[functions.regenerate_audio]
verify_jwt = false

[functions.batch_regenerate_audio]
verify_jwt = false

[functions.verify_pin]
verify_jwt = false

[functions.usage_snapshot]
verify_jwt = false

[functions.list_voices]
verify_jwt = false
