/**
 * Vercel build: writes js/config.js from SUPABASE_URL + SUPABASE_ANON_KEY.
 * Set those in: Vercel → Project → Settings → Environment Variables.
 */
const fs = require("fs");
const path = require("path");

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_ANON_KEY;

if (url && key) {
  const out = `/** Generated by vercel-build.js — do not edit on deploy; use Vercel env vars. */\nwindow.NIHONGO_CONFIG = ${JSON.stringify(
    { SUPABASE_URL: url, SUPABASE_ANON_KEY: key },
    null,
    2,
  )};\n`;
  fs.writeFileSync(path.join(__dirname, "js", "config.js"), out, "utf8");
  console.log("vercel-build: wrote js/config.js");
} else if (process.env.VERCEL) {
  console.error(
    "vercel-build: missing SUPABASE_URL or SUPABASE_ANON_KEY in Vercel Environment Variables",
  );
  process.exit(1);
} else {
  console.log(
    "vercel-build: skipping (no SUPABASE_* env); keeping existing js/config.js for local dev",
  );
}
